// Generated by gencpp from file objectmapping/ObjectData.msg
// DO NOT EDIT!


#ifndef OBJECTMAPPING_MESSAGE_OBJECTDATA_H
#define OBJECTMAPPING_MESSAGE_OBJECTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace objectmapping
{
template <class ContainerAllocator>
struct ObjectData_
{
  typedef ObjectData_<ContainerAllocator> Type;

  ObjectData_()
    : header()
    , image_rgb()
    , image_depth()
    , constant(0.0)
    , reference_board_pose()
    , reference_camera_pose()  {
    }
  ObjectData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_rgb(_alloc)
    , image_depth(_alloc)
    , constant(0.0)
    , reference_board_pose(_alloc)
    , reference_camera_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_rgb_type;
  _image_rgb_type image_rgb;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_depth_type;
  _image_depth_type image_depth;

   typedef float _constant_type;
  _constant_type constant;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _reference_board_pose_type;
  _reference_board_pose_type reference_board_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _reference_camera_pose_type;
  _reference_camera_pose_type reference_camera_pose;





  typedef boost::shared_ptr< ::objectmapping::ObjectData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objectmapping::ObjectData_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectData_

typedef ::objectmapping::ObjectData_<std::allocator<void> > ObjectData;

typedef boost::shared_ptr< ::objectmapping::ObjectData > ObjectDataPtr;
typedef boost::shared_ptr< ::objectmapping::ObjectData const> ObjectDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::objectmapping::ObjectData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::objectmapping::ObjectData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace objectmapping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'objectmapping': ['/home/ruthz/detection_ws/src/objectmapping/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::objectmapping::ObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::objectmapping::ObjectData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::objectmapping::ObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::objectmapping::ObjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::objectmapping::ObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::objectmapping::ObjectData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::objectmapping::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca0c328fc80312b47a3bd0528ef96ca7";
  }

  static const char* value(const ::objectmapping::ObjectData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca0c328fc80312b4ULL;
  static const uint64_t static_value2 = 0x7a3bd0528ef96ca7ULL;
};

template<class ContainerAllocator>
struct DataType< ::objectmapping::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "objectmapping/ObjectData";
  }

  static const char* value(const ::objectmapping::ObjectData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::objectmapping::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
sensor_msgs/Image image_rgb\n\
sensor_msgs/Image image_depth\n\
float32 constant\n\
geometry_msgs/PoseStamped reference_board_pose\n\
geometry_msgs/PoseStamped reference_camera_pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::objectmapping::ObjectData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::objectmapping::ObjectData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_rgb);
      stream.next(m.image_depth);
      stream.next(m.constant);
      stream.next(m.reference_board_pose);
      stream.next(m.reference_camera_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::objectmapping::ObjectData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::objectmapping::ObjectData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_rgb: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_rgb);
    s << indent << "image_depth: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_depth);
    s << indent << "constant: ";
    Printer<float>::stream(s, indent + "  ", v.constant);
    s << indent << "reference_board_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_board_pose);
    s << indent << "reference_camera_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_camera_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECTMAPPING_MESSAGE_OBJECTDATA_H
