(cl:defpackage obj_recognition-msg
  (:use )
  (:export
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTSARRAY>"
   "DETECTEDOBJECTSARRAY"
   "<SEGMENTEDCLUSTERSARRAY>"
   "SEGMENTEDCLUSTERSARRAY"
  ))

