// Generated by gencpp from file obj_recognition/GetNormals.msg
// DO NOT EDIT!


#ifndef OBJ_RECOGNITION_MESSAGE_GETNORMALS_H
#define OBJ_RECOGNITION_MESSAGE_GETNORMALS_H

#include <ros/service_traits.h>


#include <obj_recognition/GetNormalsRequest.h>
#include <obj_recognition/GetNormalsResponse.h>


namespace obj_recognition
{

struct GetNormals
{

typedef GetNormalsRequest Request;
typedef GetNormalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNormals
} // namespace obj_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::obj_recognition::GetNormals > {
  static const char* value()
  {
    return "0a9bb8a1d7550c14c769843382adf4ac";
  }

  static const char* value(const ::obj_recognition::GetNormals&) { return value(); }
};

template<>
struct DataType< ::obj_recognition::GetNormals > {
  static const char* value()
  {
    return "obj_recognition/GetNormals";
  }

  static const char* value(const ::obj_recognition::GetNormals&) { return value(); }
};


// service_traits::MD5Sum< ::obj_recognition::GetNormalsRequest> should match 
// service_traits::MD5Sum< ::obj_recognition::GetNormals > 
template<>
struct MD5Sum< ::obj_recognition::GetNormalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::obj_recognition::GetNormals >::value();
  }
  static const char* value(const ::obj_recognition::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::obj_recognition::GetNormalsRequest> should match 
// service_traits::DataType< ::obj_recognition::GetNormals > 
template<>
struct DataType< ::obj_recognition::GetNormalsRequest>
{
  static const char* value()
  {
    return DataType< ::obj_recognition::GetNormals >::value();
  }
  static const char* value(const ::obj_recognition::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::obj_recognition::GetNormalsResponse> should match 
// service_traits::MD5Sum< ::obj_recognition::GetNormals > 
template<>
struct MD5Sum< ::obj_recognition::GetNormalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::obj_recognition::GetNormals >::value();
  }
  static const char* value(const ::obj_recognition::GetNormalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::obj_recognition::GetNormalsResponse> should match 
// service_traits::DataType< ::obj_recognition::GetNormals > 
template<>
struct DataType< ::obj_recognition::GetNormalsResponse>
{
  static const char* value()
  {
    return DataType< ::obj_recognition::GetNormals >::value();
  }
  static const char* value(const ::obj_recognition::GetNormalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJ_RECOGNITION_MESSAGE_GETNORMALS_H
